builders:

  routesBuilder:
    import: "package:oobium_routing_gen/builders.dart"
    builder_factories: ["routesBuilder"]
    build_extensions: {"routes.dart": ["routes.g.dart", "routes.g.provider.dart"]}
    build_to: source
    auto_apply: root_package
