// Mocks generated by Mockito 5.0.9 from annotations
// in firebase_auth_validator/test/firebase_auth_validator_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oobium/src/data/models.dart' as _i5;
import 'package:oobium_server/src/server.dart' as _i7;
import 'package:oobium_server/src/service.dart' as _i2;
import 'package:oobium_server/src/services/auth_service.dart' as _i4;
import 'package:oobium_server/src/services/auth_service.schema.gen.models.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeServices<P> extends _i1.Fake implements _i2.Services<P> {}

class _FakeType extends _i1.Fake implements Type {}

class _FakeGroup extends _i1.Fake implements _i3.Group {}

class _FakeMembership extends _i1.Fake implements _i3.Membership {}

class _FakeUser extends _i1.Fake implements _i3.User {}

class _FakeLink extends _i1.Fake implements _i3.Link {}

class _FakeToken extends _i1.Fake implements _i3.Token {}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get root =>
      (super.noSuchMethod(Invocation.getter(#root), returnValue: '') as String);
  @override
  _i2.Services<_i4.AuthConnection> get services =>
      (super.noSuchMethod(Invocation.getter(#services),
              returnValue: _FakeServices<_i4.AuthConnection>())
          as _i2.Services<_i4.AuthConnection>);
  @override
  Type get consumes => (super.noSuchMethod(Invocation.getter(#consumes),
      returnValue: _FakeType()) as Type);
  @override
  Type get provides => (super.noSuchMethod(Invocation.getter(#provides),
      returnValue: _FakeType()) as Type);
  @override
  bool any(String? id) =>
      (super.noSuchMethod(Invocation.method(#any, [id]), returnValue: false)
          as bool);
  @override
  bool none(String? id) =>
      (super.noSuchMethod(Invocation.method(#none, [id]), returnValue: false)
          as bool);
  @override
  List<T?> batch<T extends _i5.DataModel>(
          {Iterable<T>? put, Iterable<String?>? remove}) =>
      (super.noSuchMethod(
          Invocation.method(#batch, [], {#put: put, #remove: remove}),
          returnValue: <T?>[]) as List<T?>);
  @override
  _i3.Group? getGroup(String? id) =>
      (super.noSuchMethod(Invocation.method(#getGroup, [id])) as _i3.Group?);
  @override
  Iterable<_i3.Group> getGroups() =>
      (super.noSuchMethod(Invocation.method(#getGroups, []), returnValue: [])
          as Iterable<_i3.Group>);
  @override
  _i3.Group putGroup(_i3.Group? group) =>
      (super.noSuchMethod(Invocation.method(#putGroup, [group]),
          returnValue: _FakeGroup()) as _i3.Group);
  @override
  _i3.Group? removeGroup(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeGroup, [id])) as _i3.Group?);
  @override
  _i3.Membership? getMembership(String? id) =>
      (super.noSuchMethod(Invocation.method(#getMembership, [id]))
          as _i3.Membership?);
  @override
  Iterable<_i3.Membership> getMemberships() => (super
          .noSuchMethod(Invocation.method(#getMemberships, []), returnValue: [])
      as Iterable<_i3.Membership>);
  @override
  _i3.Membership putMembership(_i3.Membership? membership) =>
      (super.noSuchMethod(Invocation.method(#putMembership, [membership]),
          returnValue: _FakeMembership()) as _i3.Membership);
  @override
  _i3.Membership? removeMembership(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeMembership, [id]))
          as _i3.Membership?);
  @override
  _i3.User? getUser(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUser, [id])) as _i3.User?);
  @override
  Iterable<_i3.User> getUsers() =>
      (super.noSuchMethod(Invocation.method(#getUsers, []), returnValue: [])
          as Iterable<_i3.User>);
  @override
  _i3.User putUser(_i3.User? user) =>
      (super.noSuchMethod(Invocation.method(#putUser, [user]),
          returnValue: _FakeUser()) as _i3.User);
  @override
  _i3.User? removeUser(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeUser, [id])) as _i3.User?);
  @override
  _i3.Link? getLink(String? id) =>
      (super.noSuchMethod(Invocation.method(#getLink, [id])) as _i3.Link?);
  @override
  Iterable<_i3.Link> getLinks() =>
      (super.noSuchMethod(Invocation.method(#getLinks, []), returnValue: [])
          as Iterable<_i3.Link>);
  @override
  _i3.Link putLink(_i3.Link? link) =>
      (super.noSuchMethod(Invocation.method(#putLink, [link]),
          returnValue: _FakeLink()) as _i3.Link);
  @override
  _i3.Link? removeLink(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeLink, [id])) as _i3.Link?);
  @override
  _i3.Token? getToken(String? id) =>
      (super.noSuchMethod(Invocation.method(#getToken, [id])) as _i3.Token?);
  @override
  Iterable<_i3.Token> getTokens() =>
      (super.noSuchMethod(Invocation.method(#getTokens, []), returnValue: [])
          as Iterable<_i3.Token>);
  @override
  _i3.Token putToken(_i3.Token? token) =>
      (super.noSuchMethod(Invocation.method(#putToken, [token]),
          returnValue: _FakeToken()) as _i3.Token);
  @override
  _i6.Stream<_i5.DataModelEvent<_i5.DataModel>> streamAll() =>
      (super.noSuchMethod(Invocation.method(#streamAll, []),
              returnValue: Stream<_i5.DataModelEvent<_i5.DataModel>>.empty())
          as _i6.Stream<_i5.DataModelEvent<_i5.DataModel>>);
  @override
  _i6.Stream<_i5.DataModelEvent<_i3.Group>> streamGroups(
          {bool Function(_i3.Group)? where}) =>
      (super.noSuchMethod(Invocation.method(#streamGroups, [], {#where: where}),
              returnValue: Stream<_i5.DataModelEvent<_i3.Group>>.empty())
          as _i6.Stream<_i5.DataModelEvent<_i3.Group>>);
  @override
  _i6.Stream<_i5.DataModelEvent<_i3.Membership>> streamMemberships(
          {bool Function(_i3.Membership)? where}) =>
      (super.noSuchMethod(
              Invocation.method(#streamMemberships, [], {#where: where}),
              returnValue: Stream<_i5.DataModelEvent<_i3.Membership>>.empty())
          as _i6.Stream<_i5.DataModelEvent<_i3.Membership>>);
  @override
  _i6.Stream<_i5.DataModelEvent<_i3.User>> streamUsers(
          {bool Function(_i3.User)? where}) =>
      (super.noSuchMethod(Invocation.method(#streamUsers, [], {#where: where}),
              returnValue: Stream<_i5.DataModelEvent<_i3.User>>.empty())
          as _i6.Stream<_i5.DataModelEvent<_i3.User>>);
  @override
  _i3.Token? consume(String? code) =>
      (super.noSuchMethod(Invocation.method(#consume, [code])) as _i3.Token?);
  @override
  String? getUserToken(String? uid, {bool? forceNew = false}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserToken, [uid], {#forceNew: forceNew}))
          as String?);
  @override
  _i3.User? updateUserToken(String? uid) =>
      (super.noSuchMethod(Invocation.method(#updateUserToken, [uid]))
          as _i3.User?);
  @override
  void onAttach(_i7.Host? host) =>
      super.noSuchMethod(Invocation.method(#onAttach, [host]),
          returnValueForMissingStub: null);
  @override
  void onDetach(_i7.Host? host) =>
      super.noSuchMethod(Invocation.method(#onDetach, [host]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> onStart() =>
      (super.noSuchMethod(Invocation.method(#onStart, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> onStop() =>
      (super.noSuchMethod(Invocation.method(#onStop, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  void addValidator(_i4.AuthValidator? validator) =>
      super.noSuchMethod(Invocation.method(#addValidator, [validator]),
          returnValueForMissingStub: null);
  @override
  void setValidators(Iterable<_i4.AuthValidator>? validators) =>
      super.noSuchMethod(Invocation.method(#setValidators, [validators]),
          returnValueForMissingStub: null);
}
