builders:

  routesBuilder:
    import: "package:oobium_gen/builders.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: {".schema": [".schema.g.dart"]}
    build_to: source
    auto_apply: root_package
