// Mocks generated by Mockito 5.0.9 from annotations
// in oobium_server/test/auth_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oobium/src/datastore/models.dart' as _i8;
import 'package:oobium/src/websocket.dart' as _i4;
import 'package:oobium_server/src/server.dart' as _i6;
import 'package:oobium_server/src/server_settings.dart' as _i5;
import 'package:oobium_server/src/service.dart' as _i2;
import 'package:oobium_server/src/services/auth_service.dart' as _i7;
import 'package:oobium_server/src/services/auth_service.schema.gen.models.dart'
    as _i3;

import 'auth_service_test.dart' as _i10;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeServices<P> extends _i1.Fake implements _i2.Services<P> {}

class _FakeType extends _i1.Fake implements Type {}

class _FakeGroup extends _i1.Fake implements _i3.Group {}

class _FakeMembership extends _i1.Fake implements _i3.Membership {}

class _FakeUser extends _i1.Fake implements _i3.User {}

class _FakeLink extends _i1.Fake implements _i3.Link {}

class _FakeToken extends _i1.Fake implements _i3.Token {}

class _FakeWsResult extends _i1.Fake implements _i4.WsResult {}

class _FakeServerSettings extends _i1.Fake implements _i5.ServerSettings {}

class _FakeLogger extends _i1.Fake implements _i6.Logger {}

class _FakeWsProxy extends _i1.Fake implements _i6.WsProxy {}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get root =>
      (super.noSuchMethod(Invocation.getter(#root), returnValue: '') as String);
  @override
  _i2.Services<_i7.AuthConnection> get services =>
      (super.noSuchMethod(Invocation.getter(#services),
              returnValue: _FakeServices<_i7.AuthConnection>())
          as _i2.Services<_i7.AuthConnection>);
  @override
  Type get consumes => (super.noSuchMethod(Invocation.getter(#consumes),
      returnValue: _FakeType()) as Type);
  @override
  Type get provides => (super.noSuchMethod(Invocation.getter(#provides),
      returnValue: _FakeType()) as Type);
  @override
  bool any(String? id) =>
      (super.noSuchMethod(Invocation.method(#any, [id]), returnValue: false)
          as bool);
  @override
  bool none(String? id) =>
      (super.noSuchMethod(Invocation.method(#none, [id]), returnValue: false)
          as bool);
  @override
  List<T?> batch<T extends _i8.DataModel>(
          {Iterable<T>? put, Iterable<String?>? remove}) =>
      (super.noSuchMethod(
          Invocation.method(#batch, [], {#put: put, #remove: remove}),
          returnValue: <T?>[]) as List<T?>);
  @override
  _i3.Group? getGroup(String? id) =>
      (super.noSuchMethod(Invocation.method(#getGroup, [id])) as _i3.Group?);
  @override
  Iterable<_i3.Group> getGroups() =>
      (super.noSuchMethod(Invocation.method(#getGroups, []), returnValue: [])
          as Iterable<_i3.Group>);
  @override
  _i3.Group putGroup(_i3.Group? group) =>
      (super.noSuchMethod(Invocation.method(#putGroup, [group]),
          returnValue: _FakeGroup()) as _i3.Group);
  @override
  _i3.Group? removeGroup(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeGroup, [id])) as _i3.Group?);
  @override
  _i3.Membership? getMembership(String? id) =>
      (super.noSuchMethod(Invocation.method(#getMembership, [id]))
          as _i3.Membership?);
  @override
  Iterable<_i3.Membership> getMemberships() => (super
          .noSuchMethod(Invocation.method(#getMemberships, []), returnValue: [])
      as Iterable<_i3.Membership>);
  @override
  _i3.Membership putMembership(_i3.Membership? membership) =>
      (super.noSuchMethod(Invocation.method(#putMembership, [membership]),
          returnValue: _FakeMembership()) as _i3.Membership);
  @override
  _i3.Membership? removeMembership(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeMembership, [id]))
          as _i3.Membership?);
  @override
  _i3.User? getUser(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUser, [id])) as _i3.User?);
  @override
  Iterable<_i3.User> getUsers() =>
      (super.noSuchMethod(Invocation.method(#getUsers, []), returnValue: [])
          as Iterable<_i3.User>);
  @override
  _i3.User putUser(_i3.User? user) =>
      (super.noSuchMethod(Invocation.method(#putUser, [user]),
          returnValue: _FakeUser()) as _i3.User);
  @override
  _i3.User? removeUser(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeUser, [id])) as _i3.User?);
  @override
  _i3.Link? getLink(String? id) =>
      (super.noSuchMethod(Invocation.method(#getLink, [id])) as _i3.Link?);
  @override
  Iterable<_i3.Link> getLinks() =>
      (super.noSuchMethod(Invocation.method(#getLinks, []), returnValue: [])
          as Iterable<_i3.Link>);
  @override
  _i3.Link putLink(_i3.Link? link) =>
      (super.noSuchMethod(Invocation.method(#putLink, [link]),
          returnValue: _FakeLink()) as _i3.Link);
  @override
  _i3.Link? removeLink(String? id) =>
      (super.noSuchMethod(Invocation.method(#removeLink, [id])) as _i3.Link?);
  @override
  _i3.Token? getToken(String? id) =>
      (super.noSuchMethod(Invocation.method(#getToken, [id])) as _i3.Token?);
  @override
  Iterable<_i3.Token> getTokens() =>
      (super.noSuchMethod(Invocation.method(#getTokens, []), returnValue: [])
          as Iterable<_i3.Token>);
  @override
  _i3.Token putToken(_i3.Token? token) =>
      (super.noSuchMethod(Invocation.method(#putToken, [token]),
          returnValue: _FakeToken()) as _i3.Token);
  @override
  _i9.Stream<_i8.DataModelEvent<_i8.DataModel>> streamAll() =>
      (super.noSuchMethod(Invocation.method(#streamAll, []),
              returnValue: Stream<_i8.DataModelEvent<_i8.DataModel>>.empty())
          as _i9.Stream<_i8.DataModelEvent<_i8.DataModel>>);
  @override
  _i9.Stream<_i8.DataModelEvent<_i3.Group>> streamGroups(
          {bool Function(_i3.Group)? where}) =>
      (super.noSuchMethod(Invocation.method(#streamGroups, [], {#where: where}),
              returnValue: Stream<_i8.DataModelEvent<_i3.Group>>.empty())
          as _i9.Stream<_i8.DataModelEvent<_i3.Group>>);
  @override
  _i9.Stream<_i8.DataModelEvent<_i3.Membership>> streamMemberships(
          {bool Function(_i3.Membership)? where}) =>
      (super.noSuchMethod(
              Invocation.method(#streamMemberships, [], {#where: where}),
              returnValue: Stream<_i8.DataModelEvent<_i3.Membership>>.empty())
          as _i9.Stream<_i8.DataModelEvent<_i3.Membership>>);
  @override
  _i9.Stream<_i8.DataModelEvent<_i3.User>> streamUsers(
          {bool Function(_i3.User)? where}) =>
      (super.noSuchMethod(Invocation.method(#streamUsers, [], {#where: where}),
              returnValue: Stream<_i8.DataModelEvent<_i3.User>>.empty())
          as _i9.Stream<_i8.DataModelEvent<_i3.User>>);
  @override
  _i3.Token? consume(String? code) =>
      (super.noSuchMethod(Invocation.method(#consume, [code])) as _i3.Token?);
  @override
  String? getUserToken(String? uid, {bool? forceNew = false}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserToken, [uid], {#forceNew: forceNew}))
          as String?);
  @override
  _i3.User? updateUserToken(String? uid) =>
      (super.noSuchMethod(Invocation.method(#updateUserToken, [uid]))
          as _i3.User?);
  @override
  void onAttach(_i6.Host? host) =>
      super.noSuchMethod(Invocation.method(#onAttach, [host]),
          returnValueForMissingStub: null);
  @override
  void onDetach(_i6.Host? host) =>
      super.noSuchMethod(Invocation.method(#onDetach, [host]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<void> onStart() =>
      (super.noSuchMethod(Invocation.method(#onStart, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> onStop() =>
      (super.noSuchMethod(Invocation.method(#onStop, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i9.Future<void>);
  @override
  void addValidator(_i7.AuthValidator? validator) =>
      super.noSuchMethod(Invocation.method(#addValidator, [validator]),
          returnValueForMissingStub: null);
  @override
  void setValidators(Iterable<_i7.AuthValidator>? validators) =>
      super.noSuchMethod(Invocation.method(#setValidators, [validators]),
          returnValueForMissingStub: null);
}

/// A class which mocks [WsProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockWsProxy extends _i1.Mock implements _i6.WsProxy {
  MockWsProxy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<Iterable<_i4.WsResult>> getAll(String? path) =>
      (super.noSuchMethod(Invocation.method(#getAll, [path]),
              returnValue: Future<Iterable<_i4.WsResult>>.value([]))
          as _i9.Future<Iterable<_i4.WsResult>>);
  @override
  _i9.Future<_i4.WsResult> getAny(String? path) =>
      (super.noSuchMethod(Invocation.method(#getAny, [path]),
              returnValue: Future<_i4.WsResult>.value(_FakeWsResult()))
          as _i9.Future<_i4.WsResult>);
  @override
  _i9.Future<Iterable<_i4.WsResult>> putAll(String? path, dynamic data) =>
      (super.noSuchMethod(Invocation.method(#putAll, [path, data]),
              returnValue: Future<Iterable<_i4.WsResult>>.value([]))
          as _i9.Future<Iterable<_i4.WsResult>>);
  @override
  _i9.Future<_i4.WsResult> putAny(String? path, dynamic data) =>
      (super.noSuchMethod(Invocation.method(#putAny, [path, data]),
              returnValue: Future<_i4.WsResult>.value(_FakeWsResult()))
          as _i9.Future<_i4.WsResult>);
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i6.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  set error404Handler(_i6.RequestHandler? _error404Handler) =>
      super.noSuchMethod(Invocation.setter(#error404Handler, _error404Handler),
          returnValueForMissingStub: null);
  @override
  set error500Handler(_i6.RequestHandler? _error500Handler) =>
      super.noSuchMethod(Invocation.setter(#error500Handler, _error500Handler),
          returnValueForMissingStub: null);
  @override
  bool get livePages =>
      (super.noSuchMethod(Invocation.getter(#livePages), returnValue: false)
          as bool);
  @override
  set livePages(bool? _livePages) =>
      super.noSuchMethod(Invocation.setter(#livePages, _livePages),
          returnValueForMissingStub: null);
  @override
  _i5.ServerSettings get settings =>
      (super.noSuchMethod(Invocation.getter(#settings),
          returnValue: _FakeServerSettings()) as _i5.ServerSettings);
  @override
  _i6.Logger get logger => (super.noSuchMethod(Invocation.getter(#logger),
      returnValue: _FakeLogger()) as _i6.Logger);
  @override
  set logger(_i6.Logger? value) =>
      super.noSuchMethod(Invocation.setter(#logger, value),
          returnValueForMissingStub: null);
  @override
  void addService(_i2.Service<dynamic, dynamic>? service) =>
      super.noSuchMethod(Invocation.method(#addService, [service]),
          returnValueForMissingStub: null);
  @override
  void addServices(List<_i2.Service<dynamic, dynamic>>? services) =>
      super.noSuchMethod(Invocation.method(#addServices, [services]),
          returnValueForMissingStub: null);
  @override
  T getService<T extends _i2.Service<dynamic, dynamic>>() =>
      (super.noSuchMethod(Invocation.method(#getService, []),
          returnValue: _i10.hostShim<T>()) as T);
  @override
  void get(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#get, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void head(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#head, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void options(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#options, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void patch(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#patch, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void post(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#post, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void put(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#put, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void delete(String? path, List<_i6.RequestHandler>? handlers,
          {_i6.Logger? logger}) =>
      super.noSuchMethod(
          Invocation.method(#delete, [path, handlers], {#logger: logger}),
          returnValueForMissingStub: null);
  @override
  void static(String? directoryPath,
          {String? at,
          String Function(String)? pathBuilder,
          _i6.Logger? logger,
          dynamic optional = false}) =>
      super.noSuchMethod(
          Invocation.method(#static, [
            directoryPath
          ], {
            #at: at,
            #pathBuilder: pathBuilder,
            #logger: logger,
            #optional: optional
          }),
          returnValueForMissingStub: null);
  @override
  void redirect(String? from) =>
      super.noSuchMethod(Invocation.method(#redirect, [from]),
          returnValueForMissingStub: null);
  @override
  void subdomain(String? name) =>
      super.noSuchMethod(Invocation.method(#subdomain, [name]),
          returnValueForMissingStub: null);
  @override
  void subdomains(List<String>? names) =>
      super.noSuchMethod(Invocation.method(#subdomains, [names]),
          returnValueForMissingStub: null);
  @override
  _i6.WsProxy socket(String? uid) =>
      (super.noSuchMethod(Invocation.method(#socket, [uid]),
          returnValue: _FakeWsProxy()) as _i6.WsProxy);
}
